//
//  Client.swift
//  Assignment
//
//  Created by Group 8(Susham,Haritha,Rohan) on 11/27/17.
//  Copyright © 2017 Group 8(Susham,Haritha,Rohan). All rights reserved.
//

import Foundation

/*************************************************LinkedListImplementation*********************************************/

    //creating empty Dictionary object by providing value type of the dictionary
    var dict = Dict<(Int,Bool)>()
    var key: String="";
    var value: (Int, Bool)
    
    //Testing code for Dictionary Insert, for each i value 2i 'a's are generated as key and if the i value is even, then the dictionary value will be a tuple(i,true) else (i,false)
    for i in 1..<500
    {
        key="";
        for _ in 1...i
        {
            key+="aa"
        }
        if i % 2 == 0
        {
            value=(i,true)
        }
        else {
            value=(i,false)
        }
        dict.insert(key:key,value:value);
        
    }

    
    // Testing code for "Lookup" function, which searches for keys that are generated by the following condition:
    // for every i,key generated will be 3i 'a'

    var count:Int=0;
    for i in 1..<333
    {
        key="";
        for _ in 1...i
        {
            key+="aaa"
        }
        let searchresult = dict.lookup(key:key);
        if(searchresult != nil){
        count=count+1;
        }
    }
    if(count != 166)
    {
    print("Error, dictionary needs to have 166 matching pairs, but found:",count)
    }

    //counter function which calcualtes the number of values whose boolean value is true.
    func counter(acc: Int,key:String,value:(Int,Bool)) -> (Int) {
        var count:Int=acc;
        if(value.1 == true){
            count=count+1;
            
        }
        return count;
    }

    //higher order fold function passing the counter function as a parameter
    var value_count=dict.fold(acc: 0,function:counter);
    if(value_count != 249){
     print("Error, expected number of nodes with dictionary value bool=true is:249.But, got:",value_count)
     }


/************************************************HashImplementation*******************************************************/

    //creating empty Dictionary object for hash table implementaion by providing value type of the dictionary and the capacity for the hash table.
    var hashDict = HashDict<(Int,Bool)>(capacity: 1000)

    //Testing code for Dictionary Insert, for each i value 2i 'a's are generated as key and if the i value is even, then the dictionary value will be a tuple(i,true) else (i,false)
    var Key: String="";
    var Value: (Int, Bool)

    for i in 1..<500
    {
        key="";
        for _ in 1...i
        {
            Key+="aa"
        }
        if i % 2 == 0
        {
            Value=(i,true)
        }
        else {
            Value=(i,false)
        }
        do{
            try hashDict.insert(key:Key,value:Value);
        }
        catch HashTableError.hashTableFull{
            print("Hash table is full")
        }
        
    }

    // Testing code for "Lookup" function, which searches for keys that are generated by the following condition: for every i,key generated will be 3i 'a'
   
     var hcount:Int=0;
     var hasException:Bool=false;
     for i in 1..<333
    {
        key="";
        for _ in 1...i
        {
            key+="aaa"
        }
            let hashSearchResult = try hashDict.lookup(key:key);
            if(hashSearchResult != nil){
            hcount=hcount+1;
            }
        
    }
    if(hcount != 166 && !hasException)
    {
    print("Error, dictionary needs to have 166 lookup keys, but found:",hcount)
    }

    //higher order fold function passing the counter function as parameter
     var hashValue_count=hashDict.fold(acc: 0,function:counter);
     if(hashValue_count != 249){
     print("Error, expected number of nodes with dictionary value bool=true is:249.But, got:",hashValue_count)
     }


